### ISSUE TITLE
Had to tweak coffee file to make it work

### ISSUE THREAD

**Issue by topka** [jorgemorgado/dashing-linechart#2] opened 2016-02-22 19:32 UTC
Not a CoffeeScript pro, but the widget was not loading and I figured it was the right/left/top/bottom initialization.

Changed it to following and it worked:
`left = @get('leftMargin') || 0`
`right = left`
`right = @get('rightMargin') if @get('rightMargin')?`
`top = @get('topMargin') || 0`
`bottom = top`
`bottom = @get('bottomMargin') if @get('bottomMargin')?`

with the original code the browser (Chrome) was throwing error: SyntaxError: Unexpected token else

**Comment by sjcliffe** [comment] 2016-02-24 23:51
Just confirming this issue as I had to make the same change.

**Comment by jorgemorgado** [comment] 2016-02-26 19:32
Interesting... I'm not able to reproduce that error (running Chrome version 48.0.2564.116, 64-bit on Mac OSX). Anyway, I'm also not fluent in CoffeScript but, can you please check if the following code works? It's a bit cleaner than making the `right`/`bottom` assignment twice.

**Option 1** (nicer):

```
    left = @get('leftMargin') || 0
    right = @get('rightMargin') || left
    top = @get('topMargin') || 0
    bottom = @get('bottomMargin') || top
```

If option 1 fails, please try **option 2** (longer version):

```
    left = @get('leftMargin') || 0
    if @get('rightMargin')
      right = @get('rightMargin')
    else
      right = left

    top = @get('topMargin') || 0
    if @get('bottomMargin')
      bottom = @get('bottomMargin')
    else
      bottom = top
```

If you can confirm this works, would really appreciate. Once I have a solution that works for everybody, I'll commit the update. Thanks a lot!

**Comment by topka** [comment] 2016-03-12 13:08
Thanks @jorgemorgado! The first option worked for me and margin settings work.

**Comment by jorgemorgado** [comment] 2016-03-12 23:35
Thank you too! I've committed the change for this and other widgets that use the same logic. Closing this issue.

**Closed as completed by jorgemorgado** 2016-03-12 23:35 UTC
